// Generated by CoffeeScript 1.3.3
(function() {
  var omi;

  omi = window.OwMuchIs || (window.OwMuchIs = {});

  omi.App = {
    init: function() {
      _.bindAll(this);
    },
    setRates: function(rates) {
      this.rates = rates;
      if (window.location.search != null) {
        this.doConversion();
      }
    },
    doConversion: function() {
      var amount, base, convertedAmount, currencyCodes, final, ratio, term;
      term = String(window.location.search).replace(/\+/ig, ' ').replace(/\?q=/ig, '').replace(/\//ig, '');
      console.log('term', term);
      $('input[type=search]').val(term);
      amount = Number(term.match(/[0-9?.0-9]*/));
      currencyCodes = term.match(/[a-z]{3}/ig);
      base = currencyCodes[0].toUpperCase();
      final = geoplugin_currencyCode();
      if (currencyCodes[1] != null) {
        final = currencyCodes[1].toUpperCase();
      }
      ratio = this.rates.rates[final] * (1 / this.rates.rates[base]);
      convertedAmount = ratio * amount;
      console.log(this.rates);
      $("#result").html("<p><span class=\"number\">" + (accounting.formatMoney(amount)) + "</span><span class=\"currency-code\">" + base + "</span>\nis about\n<span class=\"number\">" + (accounting.formatMoney(convertedAmount)) + "</span><span class=\"currency-code\">" + final + "</span></p>");
    }
  };

  omi.App.init();

}).call(this);
